[package]
name = "aoc"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "day1"
path="src/day1/main.rs"

[[bin]]
name = "day2"
path="src/day2/main.rs"

[[bin]]
name = "day3"
path="src/day3/main.rs"

[dependencies]
